//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LENDED_BOOK
    {
        public int ID { get; set; }
        public int ID_BOOK { get; set; }
        public int ID_STUDENT { get; set; }
        public System.DateTime LEND_DAY { get; set; }
        public bool RETURNED { get; set; }
        public bool OVERDUE { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
