CREATE DATABASE DUY1
GO
USE DUY1
GO
CREATE TABLE BOOK
(
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
    TITLE NVARCHAR(50) NOT NULL,
    AUTHOR NVARCHAR(50) NOT NULL,
    ID_CATEGORY VARCHAR(10) NOT NULL,
    PUBLISH_YEAR DATE NOT NULL,
    LOCATION NVARCHAR(30) NOT NULL,
    STATUS BIT NOT NULL
);

CREATE TABLE CATEGORY
(
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
    NAME NVARCHAR(30) NOT NULL,
    LEND_NUMBER_DAY INT
);

CREATE TABLE STUDENT
(
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
    NAME NVARCHAR(50) NOT NULL,
    CLASS VARCHAR(20) NOT NULL,
    NUMBER_PHONE VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL
);

CREATE TABLE LENDED_BOOK
(
	ID varchar(10) not null primary key,
	ID_BOOK VARCHAR(10) NOT NULL,
    ID_STUDENT VARCHAR(10) NOT NULL,
    LEND_DAY DATE NOT NULL,
    EXPIRATION_DAY DATE ,
    EXPIRED BIT NOT NULL
);

CREATE TABLE STAFF
(
	ID VARCHAR(20) NOT NULL ,
    NAME NVARCHAR(50) NOT NULL,
    ROLE NVARCHAR(20) NOT NULL,
    PHONENUMBER NVARCHAR(10) NOT NULL,
    EMAIL NVARCHAR(20) NOT NULL
	PRIMARY KEY(ID)
);

CREATE TABLE ACCOUNT
(
	ID_STAFF VARCHAR(20),
    USER_NAME VARCHAR(30) NOT NULL,
    PASSWORD_ID VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID_STAFF),
	FOREIGN KEY (ID_STAFF) REFERENCES STAFF(ID)

);




-- TAO KHOAI NGOAI CHO BOOK-CATEGORY
ALTER TABLE BOOK
ADD FOREIGN KEY (ID_CATEGORY)
REFERENCES CATEGORY (ID);
 
-- TAO KHOAI NGOAI CHO BOOK-LENDED_BOOK
ALTER TABLE LENDED_BOOK
ADD FOREIGN KEY (ID_BOOK)
REFERENCES BOOK(ID);

-- TAO KHOAI NGOAI CHO STUDENT-LENDED_BOOK
ALTER TABLE LENDED_BOOK
ADD FOREIGN KEY (ID_STUDENT)
REFERENCES STUDENT(ID);

